### ثبت‌ نام
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "pouria",
  "email": "pooria.babaie2002@gmail.com",
  "password": "Secret123?"
}

###  تکراری  409 
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "pouriaz",
  "email": "pooriaz.babaie2002@gmail.com",
  "password": "Secret123?"
}

### لاگین یوزرنیم
POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "pouriaz",
  "password": "Secret123?"
}

### لاگین ایمیل
POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "pooria.babaie2002@gmail.com",
  "password": "Secret123?"
}

### لاگین پسورد اشتباه 401 
POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "pouria",
  "password": "WrongPass123!"
}

### /me  توکن معتبر
GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoicG91cmlhIiwiZW1haWwiOiJwb29yaWEuYmFiYWllMjAwMkBnbWFpbC5jb20iLCJpYXQiOjE3NTUyNjM2NjksImV4cCI6MTc1NTI2NDU2OX0.5rbEqRaO0FV6hsdkK8hhOrCi5GV2I63RKdSCfRoWzkg

### /me بدون توکن ( 401 )
GET http://localhost:3000/me

### /me توکن اشتباه ( 401 )
GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoicG91cmlheiIsImVtYWlsIjoicG9vcmlhei5iYWJhaWUyMDAyQGdtYWlsLmNvbSIsImlhdCI6MTc1NTI2Mzc4MCwiZXhwIjoxNzU1MjY0NjgwfQ.9BuGJ1d3nbOzN57Pxv6EZbGiE7kjqhf66FtjuUilwv4
